name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: sudo apt-get install -y texinfo libmpc-dev libmpfr-dev libgmp-dev libgc-dev libffi-dev libunistring-dev

      - name: Run build script
        run: |
          pushd loongarch32
          ./build.sh
          popd

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: loongarch32/workbase/logs
  
